export const authErrorMessages = {
  EMAIL_REQUIRED: "Escribe tu correo electrónico.",
  EMAIL_INVALID: "Escribe un correo electrónico válido.",
  PASSWORD_REQUIRED: "Escribe tu contraseña.",
  PASSWORD_INVALID: "La contraseña no cumple la política de seguridad.",
  NAME_REQUIRED: "Escribe tu nombre.",
  PATERNAL_LAST_NAME_REQUIRED: "Escribe tu apellido.",
  INVALID_CREDENTIALS: "El correo o la contraseña son incorrectos.",
  VALIDATION_ERROR: "Revisa los campos marcados.",
  SERVER_ERROR: "No pudimos completar la acción por un problema técnico. Intenta nuevamente.",
  EMAIL_ALREADY_REGISTERED: "Ya existe una cuenta asociada a este correo. Inicia sesión o recupera tu contraseña.",
  ACCOUNT_USES_GOOGLE: "Este correo ya está vinculado con Google. Continúa con Google para acceder.",
  EMAIL_NOT_VERIFIED: "Tu correo todavía no ha sido verificado. Revisa tu bandeja o solicita un nuevo enlace.",
  ACCOUNT_BLOCKED: "Esta cuenta está temporalmente bloqueada. Inténtalo más tarde.",
  ACCOUNT_INACTIVE: "Esta cuenta está inactiva. Solicita apoyo a un administrador.",
  ORGANIZATION_INACTIVE: "Tu organización no está activa. Solicita apoyo a un administrador.",
  SESSION_CREATION_FAILED: "No pudimos crear la sesión. Intenta nuevamente.",
  OAUTH_ACCOUNT_CONFLICT: "No pudimos vincular esta cuenta de Google porque existe una configuración incompatible.",
  OAUTH_PROVIDER_ERROR: "No pudimos completar la validación con Google. Intenta nuevamente.",
  TERMS_REQUIRED: "Debes aceptar los términos para continuar.",
  WEAK_PASSWORD: "La contraseña no cumple la política de seguridad.",
  PASSWORD_MISMATCH: "Las contraseñas no coinciden.",
  SESSION_REQUIRED: "Inicia sesión para acceder al sistema.",
  ORGANIZATION_ACCESS_DENIED: "No tienes acceso a la organización solicitada.",
  PERMISSION_DENIED: "No tienes permisos para realizar esta acción.",
  FEATURE_NOT_INCLUDED: "Tu plan no incluye esta funcionalidad.",
  FEATURE_LIMIT_REACHED: "Alcanzaste el límite disponible para esta funcionalidad.",
  SUBSCRIPTION_REQUIRED: "Esta funcionalidad requiere una suscripción activa.",
  RESOURCE_STATE_INVALID: "El recurso no está en un estado válido para esta acción.",
  INVALID_OR_EXPIRED_TOKEN: "El enlace no es válido o ya expiró.",
  PASSWORD_RESET_SENT: "Si existe una cuenta asociada a ese correo, enviaremos instrucciones para restablecer la contraseña.",
  EMAIL_VERIFICATION_SENT: "Enviaremos un enlace de verificación si la cuenta puede recibirlo.",
  GOOGLE_NOT_CONFIGURED: "El acceso con Google todavía no está configurado.",
  RATE_LIMITED: "Demasiados intentos. Espera unos minutos antes de volver a intentarlo.",
} as const;

export type AuthErrorCode = keyof typeof authErrorMessages;

export type AuthFeedbackSeverity = "info" | "warning" | "error" | "success";

export const authErrorSeverity = {
  EMAIL_REQUIRED: "warning",
  EMAIL_INVALID: "warning",
  PASSWORD_REQUIRED: "warning",
  PASSWORD_INVALID: "warning",
  NAME_REQUIRED: "warning",
  PATERNAL_LAST_NAME_REQUIRED: "warning",
  INVALID_CREDENTIALS: "error",
  VALIDATION_ERROR: "warning",
  SERVER_ERROR: "error",
  EMAIL_ALREADY_REGISTERED: "warning",
  ACCOUNT_USES_GOOGLE: "warning",
  EMAIL_NOT_VERIFIED: "warning",
  ACCOUNT_BLOCKED: "warning",
  ACCOUNT_INACTIVE: "warning",
  ORGANIZATION_INACTIVE: "warning",
  SESSION_CREATION_FAILED: "error",
  OAUTH_ACCOUNT_CONFLICT: "warning",
  OAUTH_PROVIDER_ERROR: "error",
  TERMS_REQUIRED: "warning",
  WEAK_PASSWORD: "warning",
  PASSWORD_MISMATCH: "warning",
  SESSION_REQUIRED: "warning",
  ORGANIZATION_ACCESS_DENIED: "warning",
  PERMISSION_DENIED: "warning",
  FEATURE_NOT_INCLUDED: "info",
  FEATURE_LIMIT_REACHED: "warning",
  SUBSCRIPTION_REQUIRED: "warning",
  RESOURCE_STATE_INVALID: "warning",
  INVALID_OR_EXPIRED_TOKEN: "warning",
  PASSWORD_RESET_SENT: "success",
  EMAIL_VERIFICATION_SENT: "success",
  GOOGLE_NOT_CONFIGURED: "warning",
  RATE_LIMITED: "warning",
} satisfies Record<AuthErrorCode, AuthFeedbackSeverity>;
