export const authErrorMessages = {
  EMAIL_REQUIRED: "Escribe tu correo electronico.",
  EMAIL_INVALID: "Escribe un correo electronico valido.",
  PASSWORD_REQUIRED: "Escribe tu contrasena.",
  PASSWORD_INVALID: "La contrasena no cumple la politica de seguridad.",
  NAME_REQUIRED: "Escribe tu nombre.",
  PATERNAL_LAST_NAME_REQUIRED: "Escribe tu apellido.",
  INVALID_CREDENTIALS: "El correo o la contrasena son incorrectos.",
  VALIDATION_ERROR: "Revisa los campos marcados.",
  SERVER_ERROR: "No pudimos completar la accion por un problema tecnico. Intenta nuevamente.",
  EMAIL_ALREADY_REGISTERED: "Ya existe una cuenta asociada a este correo. Inicia sesion o recupera tu contrasena.",
  ACCOUNT_USES_GOOGLE: "Este correo ya esta vinculado con Google. Continua con Google para acceder.",
  EMAIL_NOT_VERIFIED: "Tu correo todavia no ha sido verificado. Revisa tu bandeja o solicita un nuevo enlace.",
  ACCOUNT_BLOCKED: "Esta cuenta esta temporalmente bloqueada. Intentalo mas tarde.",
  ACCOUNT_INACTIVE: "Esta cuenta esta inactiva. Solicita apoyo a un administrador.",
  ORGANIZATION_INACTIVE: "Tu organizacion no esta activa. Solicita apoyo a un administrador.",
  SESSION_CREATION_FAILED: "No pudimos crear la sesion. Intenta nuevamente.",
  OAUTH_ACCOUNT_CONFLICT: "No pudimos vincular esta cuenta de Google porque existe una configuracion incompatible.",
  OAUTH_PROVIDER_ERROR: "No pudimos completar la validacion con Google. Intenta nuevamente.",
  TERMS_REQUIRED: "Debes aceptar los terminos para continuar.",
  WEAK_PASSWORD: "La contrasena no cumple la politica de seguridad.",
  PASSWORD_MISMATCH: "Las contrasenas no coinciden.",
  SESSION_REQUIRED: "Inicia sesion para acceder al sistema.",
  ORGANIZATION_ACCESS_DENIED: "No tienes acceso a la organizacion solicitada.",
  PERMISSION_DENIED: "No tienes permisos para realizar esta accion.",
  FEATURE_NOT_INCLUDED: "Tu plan no incluye esta funcionalidad.",
  FEATURE_LIMIT_REACHED: "Alcanzaste el limite disponible para esta funcionalidad.",
  SUBSCRIPTION_REQUIRED: "Esta funcionalidad requiere una suscripcion activa.",
  RESOURCE_STATE_INVALID: "El recurso no esta en un estado valido para esta accion.",
  INVALID_OR_EXPIRED_TOKEN: "El enlace no es valido o ya expiro.",
  PASSWORD_RESET_SENT: "Si existe una cuenta asociada a ese correo, enviaremos instrucciones para restablecer la contrasena.",
  EMAIL_VERIFICATION_SENT: "Enviaremos un enlace de verificacion si la cuenta puede recibirlo.",
  GOOGLE_NOT_CONFIGURED: "El acceso con Google todavia no esta configurado.",
  RATE_LIMITED: "Demasiados intentos. Espera unos minutos antes de volver a intentarlo.",
} as const;

export type AuthErrorCode = keyof typeof authErrorMessages;

export type AuthFeedbackSeverity = "info" | "warning" | "error" | "success";

export const authErrorSeverity = {
  EMAIL_REQUIRED: "warning",
  EMAIL_INVALID: "warning",
  PASSWORD_REQUIRED: "warning",
  PASSWORD_INVALID: "warning",
  NAME_REQUIRED: "warning",
  PATERNAL_LAST_NAME_REQUIRED: "warning",
  INVALID_CREDENTIALS: "error",
  VALIDATION_ERROR: "warning",
  SERVER_ERROR: "error",
  EMAIL_ALREADY_REGISTERED: "warning",
  ACCOUNT_USES_GOOGLE: "warning",
  EMAIL_NOT_VERIFIED: "warning",
  ACCOUNT_BLOCKED: "warning",
  ACCOUNT_INACTIVE: "warning",
  ORGANIZATION_INACTIVE: "warning",
  SESSION_CREATION_FAILED: "error",
  OAUTH_ACCOUNT_CONFLICT: "warning",
  OAUTH_PROVIDER_ERROR: "error",
  TERMS_REQUIRED: "warning",
  WEAK_PASSWORD: "warning",
  PASSWORD_MISMATCH: "warning",
  SESSION_REQUIRED: "warning",
  ORGANIZATION_ACCESS_DENIED: "warning",
  PERMISSION_DENIED: "warning",
  FEATURE_NOT_INCLUDED: "info",
  FEATURE_LIMIT_REACHED: "warning",
  SUBSCRIPTION_REQUIRED: "warning",
  RESOURCE_STATE_INVALID: "warning",
  INVALID_OR_EXPIRED_TOKEN: "warning",
  PASSWORD_RESET_SENT: "success",
  EMAIL_VERIFICATION_SENT: "success",
  GOOGLE_NOT_CONFIGURED: "warning",
  RATE_LIMITED: "warning",
} satisfies Record<AuthErrorCode, AuthFeedbackSeverity>;
